---

#=================== Ubuntu Servers ======================
- hosts: Ubuntu_servers
  gather_facts: false
  become: true
  tasks:

  - name: update the ubuntu repos and install packages
    tags: ubuntu
    package: 
        name:
# "*" ==> Upgrades all the packages
          #  - "*"
           - htop
           - stress-ng 
        state: latest
        update_cache: yes


#==================== Linux Lite =======================
- hosts: Linux_lite_server
  vars:
       ansible_python_interpreter: /usr/bin/python
       ansible_connection: ssh
       scp_if_ssh: true
  gather_facts: false
  become: true
  tasks:

  - name: update the linux lite repos and install packages
    tags: lite
    package:
        name:
# "*" ==> Upgrades all the packages
          #  - "*"
           - htop
           - stress-ng
           - traceroute
        state: latest
        update_cache: yes


#=================== Pop server ========================
- hosts: Pop_server
#  vars:
#       ansible_python_interpreter: /usr/bin/python
  gather_facts: false
  become: true
  tasks:

  - name: update the pop repos and install packages
    tags: pop 
    package:
        name:
          #  - "*"
           - htop
           - stress-ng
        state: latest
        update_cache: yes


#=================== CentOS Server ========================
- hosts: CentOS_servers
  vars:
       ansible_python_interpreter: /usr/bin/python
  gather_facts: false
  become: true
  become_method: su
  become_user: root
  tasks:

  - name: update the centos repos and install packages
    tags: centos
    package:
        name:
           - "*" 
          #  - epel-release
          #  - htop
          #  - httpd
          #  - stress-ng 
        state: latest
        update_cache: yes


