---

- hosts: Ubuntu_servers
  become: true
  tasks:

  - name: update the repo and install apache package
    package:
        name: 
           - "{{ apache_package }}"
           -  "{{ stress_package }}"
        state: latest
        update_cache: yes

- hosts: Linuxlite
  vars:
        ansible_python_interpreter: /usr/bin/python3
  remote_user: amit
  gather_facts: no
  tasks:
  
  - name: update the repo and install stress-ng
    package:
       name:
          - "{{ apache_package }}"
          - "{{ stress_package }}"

- hosts: CentOS_servers
  become: yes
  tasks:

  - name: update the repo and install apache package
    package:
        name:
           - "{{ apache_package }}"
           -  "{{ stress_package }}"
        state: latest
        update_cache: yes
        ansible_python_interpreter: /usr/bin/python

