---

- hosts: Ubuntu_servers
  become: true
  tasks:

  - name: update the repo and install apache package
    package:
        name: 
           - "{{ apache_package }}"
           -  "{{ stress_package }}"
        state: latest
        update_cache: yes


- hosts: CentOS_servers
  become:true
  tasks:

  - name: update the repo and install apache package
    package:
        name:
           - "{{ apache_package }}"
           -  "{{ stress_package }}"
        state: latest
        update_cache: yes

